module.exports = async () => {
  throw new Error('tester runs into error.');
}
